# Generated by Django 3.2 on 2021-04-22 13:49

import api.models
import api.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0002_auto_20210420_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='framerate',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='height',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='width',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='framerate',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='height',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='width',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='framerate',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='height',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='width',
        ),
        migrations.RemoveField(
            model_name='task',
            name='code',
        ),
        migrations.RemoveField(
            model_name='task',
            name='framerate',
        ),
        migrations.RemoveField(
            model_name='task',
            name='height',
        ),
        migrations.RemoveField(
            model_name='task',
            name='width',
        ),
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default=api.models.random_hexa_color, max_length=7, unique=True, validators=[api.validators.color_validator]),
        ),
        migrations.AddField(
            model_name='sequence',
            name='root',
            field=models.CharField(max_length=250, null=True, validators=[api.validators.path_validator]),
        ),
        migrations.AddField(
            model_name='task',
            name='entity_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='entity_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'api'), ('model', 'Sequence')), models.Q(('app_label', 'api'), ('model', 'Shot')), models.Q(('app_label', 'api'), ('model', 'Asset')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.CharField(default='untitled', max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='label',
            field=models.CharField(default='untitled', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='root',
            field=models.CharField(max_length=250, null=True, validators=[api.validators.path_validator]),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.SlugField(default='untitled'),
        ),
    ]
