# Generated by Django 3.2 on 2021-04-23 14:46

import api.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210422_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='frame',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='sequence',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='shot',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 14, 46, 18, 831273)),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.SlugField(default='untitled', unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 14, 46, 18, 831273)),
        ),
        migrations.AlterField(
            model_name='frame',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 14, 46, 18, 831273)),
        ),
        migrations.AlterField(
            model_name='frame',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 14, 46, 18, 831273)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 14, 46, 18, 831273)),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.SlugField(default='untitled', unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='root',
            field=models.CharField(max_length=250, null=True, unique=True, validators=[api.validators.path_validator]),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 14, 46, 18, 831273)),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 14, 46, 18, 831273)),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='root',
            field=models.CharField(max_length=250, null=True, unique=True, validators=[api.validators.path_validator]),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 14, 46, 18, 831273)),
        ),
        migrations.AlterField(
            model_name='shot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 14, 46, 18, 831273)),
        ),
        migrations.AlterField(
            model_name='shot',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 14, 46, 18, 831273)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 14, 46, 18, 831273)),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 14, 46, 18, 831273)),
        ),
    ]
