version: "3.9"
   
services:
  silex-db-prod:
    image: postgres
    container_name: silex-db-prod
    volumes:
      - silex_db_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=silex
      - POSTGRES_USER=pipeline
      - POSTGRES_PASSWORD=pipeline
    ports:
      - "5433:5432"
    networks:
      - silex
  silex-api-beta:
    build:
      context: .
      dockerfile: Dockerfile
    image: silex-api-beta
    container_name: silex-api-beta
    command: bash -c "python src/manage.py makemigrations api 
      && python src/manage.py migrate 
      && python src/manage.py runserver 0.0.0.0:8000"
    environment:
      - SILEX_BACKEND_CONFIG=beta
      - SILEX_BACKEND_SECRET_KEY
    ports:
      - "8001:8000"
    depends_on:
      - silex-db-prod
    networks:
      - silex

volumes:
  silex_db_prod:
    name: silex_db_prod

networks:
  silex:
    name: silex
    driver: bridge
