version: "3.9"
   
services:
  silex-db-dev:
    image: postgres
    container_name: silex-db-dev
    volumes:
      - silex_db_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=silex
      - POSTGRES_USER=pipeline
      - POSTGRES_PASSWORD=pipeline
    ports:
      - "5434:5432"
    networks:
      - silex
  silex-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: silex-api-dev
    container_name: silex-api-dev
    command: bash -c "python src/manage.py makemigrations api 
      && python src/manage.py migrate 
      && python src/manage.py runserver 0.0.0.0:8000"
    environment:
      - SILEX_BACKEND_CONFIG=dev
      - SILEX_BACKEND_SECRET_KEY
    ports:
      - "8002:8000"
    depends_on:
      - silex-db-dev
    networks:
      - silex

volumes:
  silex_db_dev:
    name: silex_db_dev

networks:
  silex:
    name: silex
    driver: bridge
