# Generated by Django 3.2 on 2021-05-11 22:47

import api.models.entity.named_entity.project_model
import api.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('root', models.CharField(max_length=250, null=True, validators=[api.validators.path_validator])),
                ('state', models.CharField(max_length=10, validators=[api.validators.state_validator])),
                ('framerate', models.FloatField(default=25.0)),
                ('width', models.PositiveIntegerField(default=1920)),
                ('height', models.PositiveIntegerField(default=1080)),
                ('name', models.SlugField(default='untitled', unique=True)),
                ('label', models.CharField(default='untitled', max_length=50)),
                ('color', models.CharField(default=api.models.entity.named_entity.project_model.random_hexa_color, max_length=7, validators=[api.validators.color_validator])),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('root',)},
            },
        ),
    ]
