# Generated by Django 3.2 on 2021-04-26 11:04

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210425_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='framerate',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='asset',
            name='height',
            field=models.PositiveIntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='asset',
            name='root',
            field=models.CharField(max_length=250, null=True, unique=True, validators=[api.validators.path_validator]),
        ),
        migrations.AddField(
            model_name='asset',
            name='width',
            field=models.PositiveIntegerField(default=1920),
        ),
        migrations.AddField(
            model_name='frame',
            name='framerate',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='frame',
            name='height',
            field=models.PositiveIntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='frame',
            name='root',
            field=models.CharField(max_length=250, null=True, unique=True, validators=[api.validators.path_validator]),
        ),
        migrations.AddField(
            model_name='frame',
            name='width',
            field=models.PositiveIntegerField(default=1920),
        ),
        migrations.AddField(
            model_name='shot',
            name='framerate',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='shot',
            name='height',
            field=models.PositiveIntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='shot',
            name='root',
            field=models.CharField(max_length=250, null=True, unique=True, validators=[api.validators.path_validator]),
        ),
        migrations.AddField(
            model_name='shot',
            name='width',
            field=models.PositiveIntegerField(default=1920),
        ),
        migrations.AddField(
            model_name='task',
            name='framerate',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='task',
            name='height',
            field=models.PositiveIntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='task',
            name='root',
            field=models.CharField(max_length=250, null=True, unique=True, validators=[api.validators.path_validator]),
        ),
        migrations.AddField(
            model_name='task',
            name='width',
            field=models.PositiveIntegerField(default=1920),
        ),
    ]
