# Generated by Django 3.2 on 2021-04-26 14:13

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210426_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='root',
            field=models.CharField(max_length=250, null=True, validators=[api.validators.path_validator]),
        ),
        migrations.AlterField(
            model_name='frame',
            name='root',
            field=models.CharField(max_length=250, null=True, validators=[api.validators.path_validator]),
        ),
        migrations.AlterField(
            model_name='project',
            name='root',
            field=models.CharField(max_length=250, null=True, validators=[api.validators.path_validator]),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='root',
            field=models.CharField(max_length=250, null=True, validators=[api.validators.path_validator]),
        ),
        migrations.AlterField(
            model_name='shot',
            name='root',
            field=models.CharField(max_length=250, null=True, validators=[api.validators.path_validator]),
        ),
        migrations.AlterField(
            model_name='task',
            name='root',
            field=models.CharField(max_length=250, null=True, validators=[api.validators.path_validator]),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('project', 'root'), ('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together={('index', 'project', 'sequence', 'shot'), ('project', 'sequence', 'shot', 'root')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('root',)},
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together={('project', 'root'), ('index', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='shot',
            unique_together={('project', 'sequence', 'root'), ('index', 'project', 'sequence')},
        ),
    ]
